---
- hosts: R2DC1
  gather_facts: yes
  connection: local


  tasks:
  - name: GET CREDENTIALS
    include_vars: ciscoworks.secret.yml

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"


  - name: GATHER Hostname
    ios_command:
      provider: "{{ connection }}"
      commands:
         - show hostname
    register: switch_hostname


  - debug: var=switch_hostname.stdout_lines

#  - name: Set Description of E1/3
#    ios_interface:
#      name: Eth1/3
#      description: "{{ switch_hostname.stdout | regex_replace('^.*?(CV.*?)FEIA(.*?)\\.switch.*$', '\\1CMB\\2') }}"

#  - name: Change Hostname
#    ios_command:
#      provider: "{{ connection }}"
#      commands:
#         - hostname "{{ switch_hostname.stdout | regex_replace('^.*?(CV.*?)FEIA(.*?)\\.switch.*$', '\\1CMB\\2') }}"
#    register: switch_change_hostname
#
#  - debug: var=switch_change_hostname.stdout_lines

#  - name: configure top level configuration and save it
#    nxos_config:
#      lines: hostname {{ switch_hostname.stdout | regex_replace('^.*?(CV.*?)FEIA(.*?)\\.switch.*$', '\\1CMB\\2') }}
#    save_when: modified

#  - name: Write Hostname
#    ios_config:
#      provider: "{{ connection }}"
#      lines:
#         - hostname {{ switch_hostname.stdout | regex_replace('^.*?(CV.*?)FEIA(.*?)\\.switch.*$', '\\1CMB\\2') }}
#      replace: line
#      match: strict
#
#  - debug: "{{ switch_hostname.stdout | regex_replace('^.*?(CV.*?)FEIA(.*?)\\.switch.*$', '\\1CMB\\2') }}"
